In [1]:
import numpy as np

test_array = np.array([1,4,5,8],float)
test_array

array([1., 4., 5., 8.])

In [3]:
test_list = [[1,4,5,8],[1,4,5]]
np.array(test_list,float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [4]:
test_array = np.array([1,4,5,"8"],float)
test_array

array([1., 4., 5., 8.])

In [5]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [6]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix,int).shape

(3, 4)

In [8]:
tensor_rank3=[[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor_rank3,int).ndim

3

In [9]:
np.array(tensor_rank3,int).shape

(4, 3, 4)

In [10]:
matrix = [[1,2,5,8],[1,2,5,8]]
np.array(matrix,dtype=int)

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [11]:
np.array(matrix,dtype=float)

array([[1., 2., 5., 8.],
       [1., 2., 5., 8.]])

In [17]:
x=np.array(matrix,int)
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [16]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [18]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)